#######################
# General Configuration
#######################
language: java
sudo: false
jdk:
  - openjdk8
os:
  - linux
dist: trusty

install: true

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      - vaader-ietr:EEtUq0RrGRpHSXWZiEApSDwS#preesm

addons:
  sonarcloud:
    organization: "preesm-sonarcloud-org"
    token:
      secure: "7edfa331c5de80bf665aee04f0e9dbcbc3efa122"
    branches: .*

script: 
  - ./releng/build_and_test.sh --fast

