#######################
# General Configuration
#######################
language: java
sudo: false
jdk:
  - openjdk8
os:
  - linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

addons:
  sonarcloud:
    organization: "preesm-sonarcloud-org"
    token:
      secure: "7edfa331c5de80bf665aee04f0e9dbcbc3efa122"
    branches: .*

#enable Maven local repo caching
cache:
  directories:
  - $HOME/.m2

#######################
# Actual build stages
#######################
# The following job can be reproduced on any machine in a single line
# with the following:
#
# mvn -U -e -C -V -P releng clean checkstyle:check package verify -fae
#
# Note that sonar and findbugs are disable since they not proper config.
# The job is separated in several stages to detect quickly where the
# issue is comming from.
#######################

jobs:
  include:
    - stage : Validate POM
      script: mvn -U -e -C -B -V -P doUpdateSite -Dtycho.mode=maven help:help -q
    - stage : Fetch Maven Dependencies
      script: mvn -U -e -C -B -V -P doUpdateSite -Dtycho.mode=maven dependency:go-offline
    - stage : Run Checkstyle (offline)
      script: mvn --offline -e -C -B -V -Dtycho.mode=maven checkstyle:check
    - stage : Fetch P2 Dependencies
      script: mvn -U -e -C -B -V -P doUpdateSite help:help
    - stage : Clean (offline)
      script: mvn --offline -e -C -B -V -P doUpdateSite -Dtycho.mode=maven clean
    - stage : Build code and package (offline, no tests)
      script: mvn --offline -e -C -B -V package -fae -Dmaven.test.skip=true
    - stage : Test and run sonar (offline)
      script: mvn --offline -e -C -B -V verify sonar:sonar -fae
    - stage : Package Update-Site (offline, no tests)
      script: mvn --offline -e -C -B -V -P doUpdateSite package -fae -Dmaven.test.skip=true

#skip install step before each stage by running the /bin/true command
install: true
